name: CI on Push and Pull Request

on: [push, pull_request]

jobs:
  Android:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Android
      run: |
        cd src
        cd CoBuster
        nuget restore
        cd CoBuster.Android
        msbuild CoBuster.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
        
  iOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: iOS
      run: |
        cd src
        cd CoBuster
        nuget restore
        msbuild CoBuster.iOS/CoBuster.iOS.csproj /verbosity:normal /t:Rebuild /p:Platform=iPhoneSimulator /p:Configuration=Debug
